# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cVtE3l_hr8wZD6KpjBCm4-3Rj8iqRle
"""

s = input("Enter 3 real number (separeted by space): ")
s = s.split()
a = float(s[0])
b = float(s[1])
c = float(s[2])
print(f"a = {a}, b = {b}, c = {c}")
if a == 0:
    # Phương trình trở thành bx + c = 0
    if b == 0:
        if c == 0:
            print("Phương trình vô số nghiệm.")
        else:
            print("Phương trình vô nghiệm.")
    else:
        x = -c / b
        print(f"Phương trình có một nghiệm duy nhất: x = {x}")
else:
    # Giải phương trình bậc 2
    delta = b**2 - 4*a*c
    print(f"Delta = {delta}")

    if delta > 0:
        x1 = (-b + delta**0.5) / (2*a)
        x2 = (-b - delta**0.5) / (2*a)
        print(f"Phương trình có 2 nghiệm phân biệt: x1 = {x1}, x2 = {x2}")
    elif delta == 0:
        x = -b / (2*a)
        print(f"Phương trình có nghiệm kép: x = {x}")
    else:
        print("Phương trình vô nghiệm (delta < 0).")
   # Enter your code from here