# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kcqUbpABDKm_Nh_P4sjweQZa8Kp9zep_

# Mục mới
"""

print("hello")
print(5 / 8)
print("Hello Python")
print(5 + 5)
print(5 - 5)
print(3 * 5)
print(10 / 2)
print(4 ** 2)
print(18 % 7)
print(1000 * 1.1**15)
x = 5
print(x)
x = 1000
print(x)
savings = 1000
factor   = 1.1
result = savings * factor ** 15
print (result)
desc = 'Data Science'
profitable = True
a = 10
print(type(a))
print(type(savings))
print(type(factor))
print(type(desc))
print(type(profitable))
savings = 1000
factor = 1.10
desc = "Data Science"
year1 = savings * factor
print(type(year1))
doubledesc = desc * 2
print(doubledesc)
savings = 1000
result = 1000 * 1.10 ** 15
print("Tôi gửi ngân hàng $" + str(savings) + ", sau 15 năm, bây giờ tôi đã có $" + str(result) + ". Tuyệt vời!")
pi_string = "3.1415926"
pi_float = float(pi_string)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50
areas = [hall, kit, liv, bed, bath]
print(areas)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50
areas = [hall, kit, "living room", liv, bed, "bathroom", bath]
print(areas)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv]]
print(house)
print(type(house))
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
print(areas[1])
print(areas[-1])
print(areas[5])
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
eat_sleep_area = areas[3] + areas[-3]
print(eat_sleep_area)
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
downstairs = areas[0:6]
upstairs = areas[6:-1]
print(downstairs)
print(upstairs)
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
downstairs = areas[:6]
upstairs = areas[6:]
print(downstairs)
print(upstairs)
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
x[2][0]
x[2][:2]
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
areas[-1] = 10.50
areas[4] = 'chill zone'
print(areas)
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50]
areas_1 = areas  + ["poolhouse", 24.5]
areas_2 = list(areas_1)
areas_2.extend(["garage", 15.45])
print(areas_1)
print(areas_2)
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
del(areas[-4])
del(areas[-3])
print(areas)
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
areas_copy = list(areas)
areas_copy[0] = 5.0
print(areas)
var1 = [1, 2, 3, 4]
var2 = True
print(type(var1))
print(len(var1))
out2 = int(var2)
help(complex)
help(sorted)
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]
full = first + second
full_sorted = sorted(full, reverse=True)
print(full_sorted)

from google.colab import drive
drive.mount('/content/drive')

"""# Mục mới"""