# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvhY6s2XIA6lmc28-TltCRxdADY6Nj8c
"""

mat_khau_dung = "python123"
dem = 0
while dem < 3:
    mk = input("Nhập mật khẩu: ")
    if mk == mat_khau_dung:
        print("Đăng nhập thành công")
        break
    else:
        dem += 1
if dem == 3:
    print("Tài khoản bị khóa")