# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySsOAECU4gKK_GdzHwzH55I4ouJ6nirn
"""

gpa = float(input("Nhập GPA (0-10): "))

if gpa < 0 or gpa > 10:
    print("GPA không hợp lệ")
elif gpa >= 8.5:
    print("Xuất sắc")
elif gpa >= 7.0:
    print("Giỏi")
elif gpa >= 5.5:
    print("Khá")
elif gpa >= 4.0:
    print("Trung bình")
else:
    print("Yếu")