# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvhY6s2XIA6lmc28-TltCRxdADY6Nj8c
"""

n = int(input("Nhập số nguyên dương n: "))
tong = 0
for i in range(2, n + 1, 2):
    tong += i
print(tong)