# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-MD93tGP9Fp8Jff0MEOMUftTbLvLPo_
"""

def uscnn(a,b):
    if (b==0):
        return a;
    return uscnn(b,a%b);
a = int(input('a= '))
b = int(input('b= '))
print("Ước số chung nhỏ nhất của", a, "và", b, "là", uscnn(a,b))