# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_i3V1MtrzcWuSwUmorSVCL7g0VvnWs56
"""

# các biến thể hiện diện tích các phòng (m2)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50
# khởi tạo danh sách areas
areas = [hall, kit, liv, bed, bath]
# in ra areas
print(areas)
# các biến thể hiện diện tích các phòng (m2)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# khởi tạo danh sách areas đúng yêu cầu
areas = [
    "hallway", hall,
    "kitchen", kit,
    "living room", liv,
    "bedroom", bed,
    "bathroom", bath
]

# in ra areas
print(areas)
# các biến thể hiện diện tích các phòng (m2)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# thông tin về ngôi nhà, biểu diễn bởi danh sách của các danh sách
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv]]

# in ra giá trị của house
print(house)

# in ra kiểu dữ liệu của house
print(type(house))
# khởi tạo danh sách areas
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# in ra phần tử thứ hai của areas
print(areas[1])

# in ra phần tử cuối cùng của areas
print(areas[-1])

# in ra diện tích của phòng khách (living room)
print(areas[5])
#khởi tạo
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# tổng diện tích của kitchen và bedroom: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# in ra giá trị của eat_sleep_area
print(eat_sleep_area)
# khởi tạo
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# trích xuất các phần tử của areas để khởi tạo downstairs
downstairs = areas[0:6]

# trích xuất các phần tử của areas để khởi tạo upstairs
upstairs = areas[6:-1]

# in ra downstairs và upstairs
print(downstairs)
print(upstairs)
# khởi tạo
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# trích xuất các phần tử của areas để khởi tạo downstairs (cách 2)
downstairs = areas[:6]

# trích xuất các phần tử của areas để khởi tạo upstairs (cách 2)
upstairs = areas[6:]

# in ra downstairs và upstairs
print(downstairs)
print(upstairs)
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
x[2][0]
x[2][:2]
# khởi tạo
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# sửa lại diện tích của phòng tắm (bathroom)
areas[-1] = 10.50

# sửa "living room" thành "chill zone"
areas[4] = 'chill zone'

# in ra areas
print(areas)
# khởi tạo
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# thêm dữ liệu của poolhouse vào areas, tạo danh sách mới tên areas_1
areas_1 = areas  + ["poolhouse", 24.5]

# thêm dữ liệu của garage vào areas_1, tạo danh sách mới tên areas_2
areas_2 = list(areas_1)
areas_2.extend(["garage", 15.45])

# in ra areas_1 và areas_2
print(areas_1)
print(areas_2)
# khởi tạo
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# xóa "poolhouse"
del(areas[-4])

# xóa diện tích của poolhouse
del(areas[-3])

# in ra areas
print(areas)
# khởi tạo areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# tạo areas_copy
areas_copy = list(areas)

# thay đổi areas_copy
areas_copy[0] = 5.0

# in ra areas
print(areas)
# khởi tạo
var1 = [1, 2, 3, 4]
var2 = True

# in ra kiểu của var1
print(type(var1))

# in ra số lượng phần tử của var1
print(len(var1))

# chuyển biến var2 sang số nguyên, kết quả lưu vào biến out2
out2 = int(var2)
help(complex)
help(sorted)
# khởi tạo
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# ghép first và second vào danh sách full
full = first + second

# sắp xếp lại full theo thứ tự giảm dần, lưu vào biến full_sorted
full_sorted = sorted(full, reverse=True)

# in ra full_sorted
print(full_sorted)
# tạo xâu room
room = "poolhouse"

# sử dụng hàm upper() trên room, lưu kết quả vào room_up
room_up = room.upper()

# in ra room và room_up
print(room, room_up)

# in ra số lượng chữ cái o trong xâu room
print(len(room))
# khởi tạo
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# in ra chỉ số (index) của phần tử có giá trị 20.0
print(areas.index(20))

# in ra số lần xuất hiện của 14.5 trong areas, sử dụng phương thức count()
print(areas.count(14.5))
# khởi tạo
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# sử dụng phương thức append 2 lần để thêm dữ liệu về bể bơi và gara
areas.append(24.5)
areas.append(15.45)
# in ra areas
print(areas)

# đảo ngược lại thứ tự các phần tử trong areas
areas.reverse()

# in ra areas
print(areas)
import numpy

arr = numpy.array([1, 2, 3])

print(arr)
import numpy as np

# Sử dụng np thay cho numpy
arr = np.array([1, 2, 3])

print(arr)
# định nghĩa bán kính r
r = 0.43

# import gói "math"
import math

# tính chu vi C
C = 2 * math.pi * r

# tính diện tích S
S = math.pi * r **2

# in kết quả
print("Chu vi: " + str(C))
print("Diện tích: " + str(S))
# định nghĩa bán kính r
r = 192500

# nhập hàm radians trong gói math
from  math import radians

# dist = quãng đường Mặt Trăng di chuyển sau khi quay được 12 độ
dist = radians(12) * r

# in ra giá trị dist
print(dist)