# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cVtE3l_hr8wZD6KpjBCm4-3Rj8iqRle
"""

n = int(input("Enter a positive integer:"))
print(n)

s = 0    # biến s dùng để lưu tổng
i = 0    # bắt đầu từ số chẵn đầu tiên

while i < n:
    s += i
    i += 2   # tăng lên số chẵn tiếp theo

print(f"The sum of even numbers less than {n} is {s}")