# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRCpotAwClJbq5L87sGkKpRQPkX5h9gu
"""

n = int(input("Enter a positive integer:"))
print(n)

s = 0  # biến số dùng để lưu tổng
for i in range(n + 1):   # duyệt từ 0 đến n
    s += i               # cộng dồn

print(f"The sum of 0 to {n} is {s}")